import type { OrbitHelperPack } from './types';

export const BUNDLED_ORBIT_HELPER_PACK: OrbitHelperPack = {
  id: 'orbit-helper-core-en-001',
  name: 'Orbit Helper Core',
  locale: 'en',
  version: '2026.04.14.1',
  source: 'bundled',
  updatedAt: '2026-04-14T00:00:00.000Z',
  articles: [
    {
      id: 'add-payment',
      title: 'How do I add a payment?',
      summary: 'Record money received from a customer and update their balance.',
      tags: ['payment', 'transaction', 'customer', 'balance', 'dues'],
      screenContext: ['Dashboard', 'CustomerDetail', 'TransactionForm'],
      body: [
        'Use Add Payment when a customer pays you. A payment reduces the amount they owe.',
        'From Home, tap Add Payment. Pick the customer, enter the amount, keep today as the date unless needed, then save.',
        'From a customer page, Add Payment opens faster because the customer is already selected.',
      ],
      actions: [
        { label: 'Add Payment', target: 'TransactionForm', params: { type: 'payment' } },
        { label: 'View Customers', target: 'Customers' },
      ],
    },
    {
      id: 'add-credit',
      title: 'What does credit mean?',
      summary: 'Credit is money the customer owes you for goods or services supplied.',
      tags: ['credit', 'dues', 'transaction', 'balance', 'owe'],
      screenContext: ['Dashboard', 'CustomerDetail', 'TransactionForm'],
      body: [
        'Use Add Credit when you supply something now and the customer will pay later.',
        'Credit increases the customer balance. Payment reduces it.',
        'The customer detail page shows the running balance after each ledger entry.',
      ],
      actions: [
        { label: 'Add Credit', target: 'TransactionForm', params: { type: 'credit' } },
        { label: 'Open Customers', target: 'Customers' },
      ],
    },
    {
      id: 'customer-balance',
      title: 'How do I know who owes me?',
      summary: 'Use Home and Customers to see outstanding balances quickly.',
      tags: ['receivable', 'outstanding', 'dues', 'customers', 'follow up'],
      screenContext: ['Dashboard', 'Customers', 'CustomerDetail'],
      body: [
        'Home shows total receivable and highest dues first.',
        'Customers lets you search by name, phone, or notes and filter to outstanding balances.',
        'Open a customer to see who owes whom, total credit, total payments, and ledger history.',
      ],
      actions: [
        { label: 'Open Customers', target: 'Customers' },
        { label: 'Go Home', target: 'Dashboard' },
      ],
    },
    {
      id: 'create-invoice',
      title: 'How do I create an invoice?',
      summary: 'Create itemized invoices with products, service descriptions, tax, and PDF export.',
      tags: ['invoice', 'item', 'service', 'description', 'pdf', 'tax'],
      screenContext: ['Invoices', 'InvoiceForm', 'InvoicePreview'],
      body: [
        'Open Invoices and tap Create Invoice. Choose a customer if needed, add item names and optional service descriptions, then enter quantity and price.',
        'If tax is enabled and a local tax pack is active, tax rates can be filled from the local setup. You can still override them when needed.',
        'After saving, preview the invoice, view the actual PDF, save it locally, share it, or print it.',
      ],
      actions: [
        { label: 'Create Invoice', target: 'InvoiceForm' },
        { label: 'Open Invoices', target: 'Invoices' },
      ],
    },
    {
      id: 'statement-pdf',
      title: 'How do customer statements work?',
      summary: 'Generate a date-filtered statement PDF from a customer ledger.',
      tags: ['statement', 'pdf', 'share', 'date range', 'ledger'],
      screenContext: ['CustomerDetail', 'StatementPreview'],
      body: [
        'Open a customer and tap Statement. Choose a date range such as last 7 days, last 30 days, this month, all time, or custom.',
        'The preview shows the exact ledger entries and final balance for that range.',
        'Use View PDF for the actual PDF, or use save, share, and print actions from the document screen.',
      ],
      actions: [{ label: 'Open Customers', target: 'Customers' }],
    },
    {
      id: 'backup-restore',
      title: 'How do backups work?',
      summary: 'Export a private copy of your ledger data and restore only after preview.',
      tags: ['backup', 'restore', 'safety', 'data', 'json'],
      screenContext: ['BackupRestore', 'BusinessProfileSettings'],
      body: [
        'Backup exports a structured local file for safekeeping. Store it somewhere you trust.',
        'Restore always validates the file first and shows a preview before replacing local data.',
        'PIN and biometric unlock settings are device-only. After restoring, turn protection on again if needed.',
      ],
      actions: [{ label: 'Open Backup & Restore', target: 'BackupRestore' }],
    },
    {
      id: 'pin-security',
      title: 'How does app protection work?',
      summary: 'Protect the app with a 4-digit PIN, biometric unlock, and inactivity locking.',
      tags: ['pin', 'biometric', 'fingerprint', 'face id', 'security', 'lock', 'privacy'],
      screenContext: ['BusinessProfileSettings', 'PinManagement'],
      body: [
        'PIN protection locks Orbit Ledger on launch and after inactivity based on your timeout setting.',
        'Biometric unlock is optional and works offline through the device system. Your face or fingerprint data is never stored by Orbit Ledger.',
        'The PIN and biometric unlock setting are stored securely on this device and are not included in backup files.',
        'Critical actions like restore can ask for PIN or biometric confirmation when protection is active.',
      ],
      actions: [{ label: 'Open PIN Settings', target: 'BusinessProfileSettings' }],
    },
    {
      id: 'tax-packs',
      title: 'Why is tax zero?',
      summary: 'Tax stays zero until tax is enabled and a local tax profile or tax pack is active.',
      tags: ['tax', 'gst', 'vat', 'tax pack', 'country package', 'invoice'],
      screenContext: ['TaxSetup', 'CountryPackageStore', 'InvoiceForm'],
      body: [
        'Orbit Ledger keeps core ledger work offline. Tax calculations use local tax profiles or country packages after you install or configure them.',
        'Open Tax Setup to check online updates, install a tax pack, or enter a manual tax rate.',
        'Invoices can auto-fill item tax from the active local setup when available, and you can still override the rate.',
      ],
      actions: [
        { label: 'Open Tax Setup', target: 'TaxSetup' },
        { label: 'Open Country Store', target: 'CountryPackageStore' },
      ],
    },
    {
      id: 'country-packages',
      title: 'What are country packages?',
      summary: 'Country packages bundle tax packs, document templates, and compliance settings.',
      tags: ['country', 'package', 'templates', 'compliance', 'tax'],
      screenContext: ['CountryPackageStore', 'TaxSetup', 'ComplianceReports'],
      body: [
        'A country package installs the local business logic Orbit Ledger needs for a region: tax pack, document templates, and compliance configuration.',
        'Once installed, the package works offline. Updates can be checked when you choose.',
        'Keep simple ledger work separate: you can use customers and transactions without country packages.',
      ],
      actions: [{ label: 'Open Country Store', target: 'CountryPackageStore' }],
    },
    {
      id: 'pro-features',
      title: 'What does Pro unlock?',
      summary: 'Pro improves document branding and premium presentation without blocking core ledger work.',
      tags: ['pro', 'upgrade', 'branding', 'premium', 'pdf'],
      screenContext: ['Upgrade', 'BusinessProfileSettings', 'InvoicePreview', 'StatementPreview'],
      body: [
        'Free keeps daily ledger tools available: customers, transactions, basic PDFs, backups, restore, and PIN protection.',
        'Pro adds branded documents, premium PDF styling, custom logo and signature placement, and future advanced workflows.',
        'Upgrade prompts should stay contextual and never block basic ledger work.',
      ],
      actions: [{ label: 'View Pro Benefits', target: 'Upgrade' }],
    },
    {
      id: 'product-inventory',
      title: 'How do products and stock work?',
      summary: 'Save frequent items for faster invoices and stock awareness.',
      tags: ['products', 'inventory', 'stock', 'invoice', 'low stock'],
      screenContext: ['Products', 'InvoiceForm', 'Dashboard'],
      body: [
        'Products store a name, price, unit, and stock quantity for faster invoice creation.',
        'When inventory is enabled, selecting a product fills price and checks available stock during invoice creation.',
        'Home can show low stock signals when inventory tools are enabled.',
      ],
      actions: [{ label: 'Open Products', target: 'Products' }],
    },
  ],
};
