export const brand = {
  appName: 'Orbit Ledger',
  publisher: 'Rudraix',
  fullName: 'Orbit Ledger by Rudraix',
  mark: {
    shape: 'rounded ledger page with a quiet orbit ring and balance lines',
    tone: 'trustworthy, practical, offline business records',
  },
  colors: {
    ledgerBlue: '#1C6BD8',
    ledgerBluePressed: '#1453AA',
    ledgerBlueSurface: '#E9F1FF',
    ledgerGreen: '#0D8E7F',
    ledgerGreenPressed: '#0A6B61',
    ledgerGreenSurface: '#E3F6F3',
    ink: '#172033',
    mutedInk: '#63738A',
    paper: '#FFFFFF',
    background: '#F6F8FC',
    raised: '#FBFCFE',
    shell: '#F1F5FA',
    shellDark: '#1D2433',
    sidebar: '#F8FAFD',
    sidebarDark: '#171E2A',
    topbarGlass: 'rgba(255, 255, 255, 0.86)',
    glassLine: 'rgba(182, 194, 212, 0.78)',
    line: '#E2E9F2',
    lineStrong: '#B7C4D5',
    due: '#B3771D',
    dueSurface: '#FFF4D8',
    paid: '#167C49',
    paidSurface: '#E7F4EC',
    caution: '#B3771D',
    cautionSurface: '#FFF4D8',
    danger: '#C2413A',
    dangerSurface: '#FDE8E6',
    tax: '#6457C8',
    taxSurface: '#EEEBFF',
    premium: '#A33A74',
    premiumSurface: '#F8E9F1',
    focus: '#3E83EE',
    selectedRow: '#EFF5FF',
    tableStripe: '#FAFCFF',
    overlay: 'rgba(23, 32, 51, 0.72)',
  },
  semantics: {
    tone: 'modern, trustworthy, serious, operational, lightly futuristic',
    usage:
      'neutral surfaces first, color in actions, status, numbers, filters, chips, and selected states only',
    personality:
      'business software with modern intelligence cues, not a playful fintech toy',
  },
  iconStyle: {
    background: 'deep ledger green',
    foreground: 'white ledger sheet with restrained due and paid balance accents',
    splash: 'single centered mark on a warm off-white background',
  },
  platformExpression: {
    mobile:
      'touch-first, compact, fast, high-clarity, with stronger action prominence and large tap targets',
    web: 'premium SaaS workspace, structured, calmer, denser, and built around tables, panels, and document review',
  },
} as const;
