export const brand = {
  appName: 'Orbit Ledger',
  publisher: 'Bhaumik Mehta',
  fullName: 'Orbit Ledger by Bhaumik Mehta',
  mark: {
    shape: 'rounded ledger page with a quiet orbit ring and balance lines',
    tone: 'trustworthy, practical, offline business records',
  },
  colors: {
    ledgerBlue: '#1D6FE8',
    ledgerBluePressed: '#1557B8',
    ledgerBlueSurface: '#EAF2FF',
    ledgerGreen: '#0F9F8F',
    ledgerGreenPressed: '#0B766A',
    ledgerGreenSurface: '#E2F6F3',
    ink: '#172033',
    mutedInk: '#64748B',
    paper: '#FFFFFF',
    background: '#F7F9FC',
    raised: '#FBFCFE',
    line: '#E3E8F0',
    lineStrong: '#B8C4D6',
    due: '#B7791F',
    dueSurface: '#FFF4D6',
    paid: '#168A4A',
    paidSurface: '#E6F4EC',
    caution: '#B7791F',
    cautionSurface: '#FFF4D6',
    danger: '#C2413A',
    dangerSurface: '#FDE8E6',
    tax: '#6D5DD3',
    taxSurface: '#EFECFF',
    premium: '#C43C86',
    premiumSurface: '#FCEAF4',
  },
  iconStyle: {
    background: 'deep ledger green',
    foreground: 'white ledger sheet with restrained due and paid balance accents',
    splash: 'single centered mark on a warm off-white background',
  },
} as const;
